### ISSUE TITLE
Dragging issues?

### ISSUE THREAD

**Issue by ile** [johnpuddephatt/gutentap#3]
This seems really good. But - there might be an issue with dragging. If I'm dragging a paragraph (or anything), it seems to disappear after dropping it.

https://gutentap.letsdance.agency/

**Comment by rahulkumarsingh73690** [comment]
+1

**Comment by svenit** [comment]
+1

**Comment by johnpuddephatt** [comment]
Drag and drop code is a custom bit of ProseMirror code here: https://github.com/johnpuddephatt/gutentap/blob/a3624b6102251a7a093f8d3163f52a34c226dd00/src/utils/pm-utils.js#L104

Needs investigation as behaviour is inconsistent at the minute. I have had a look but couldn't identify a quick fix.

**Comment by johnpuddephatt** [comment]
This should now be fixed in v0.1.86.
