### ISSUE TITLE
Expose "editable" property

### ISSUE THREAD

**Issue by ericpugh** [johnpuddephatt/gutentap#5]
Hello, this is an amazing project! 

Q: Is there a way to expose the editor's [editable propery](https://tiptap.dev/docs/editor/api/editor#editable) (and maybe others)? I'm trying to create an instance of GutenTap editor that can be toggled between read/edit mode.

Perhaps a new prop? Or using [defineExpose](https://vuejs.org/api/sfc-script-setup.html#defineexpose)?

**Comment by johnpuddephatt** [comment]
Hi thanks! This is now possible.

There's an editable parameter on the component that can be true or false (defaults to true)

I've also updated the demo at https://gutentap.letsdance.agency/ to include a button that toggles editable mode.
